config/routes.rb
Rails.application.routes.draw do
  get 'job/add'

  get 'job/list'

  resources :resumes do
    member do
      get 'viewed'
    end
  end

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :resume
  belongs_to :employer
end

app/models/cover_letter.rb
class CoverLetter < ActiveRecord::Base
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :applications
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :resume
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  has_many :view_histories
  has_many :jobs
  has_one  :cover_letter
  has_many :applications
  has_and_belongs_to_many :employers
  #has_many :employers :through => :application
end

app/models/view_history.rb
class ViewHistory < ActiveRecord::Base
  belongs_to :resume
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_controller.rb
class JobController < ApplicationController
  def add
  end

  def list
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_filter :check_for_top_secret

  def check_for_top_secret
    render text: 'Not authorized', status: 403 if params[:id] && params[:id].to_i == 1
  end

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    vh = ViewHistory.new(time_viewed: Time.now, ip: request.remote_ip, resume_id: set_resume.id)
    vh.save
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def viewed

    resume = Resume.find(params[:id])
    @views = resume.view_histories

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:name, :phone, :email, :city, :state, :zip, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/job/add.html.erb
<h1>Job#add</h1>
<p>Find me in app/views/job/add.html.erb</p>

app/views/job/list.html.erb
<h1>Job#list</h1>
<p>Find me in app/views/job/list.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResumeRepository</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<%= console %>
</html>

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email.string</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= resume.phone %></td>
        <td><%= resume.email %></td>
        <td><%= resume.city %></td>
        <td><%= resume.state %></td>
        <td><%= resume.zip %></td>
        <td><%= resume.summary %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @resume.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @resume.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @resume.zip %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @resume.summary %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/viewed.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Views</h1>

<table>
  <thead>
  <tr>
    <th>Date</th>
    <th>IP</th>
  </tr>
  </thead>

  <tbody>
  <% @views.each do |view| %>
      <tr>
        <td><%= view.time_viewed %></td>
        <td><%= view.ip %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>